### ISSUE TITLE
Merge djangomanage.py and manage.py

### ISSUE THREAD

**Issue by ShaneDrury** [ShaneDrury/pyon#4]
Use the existing djangomanage.py script and merge it with manage.py rather than having two scripts to manage the same thing.

**Comment by mspraggs** [comment]
Isn't this more related to pyon-qed? Unless the manage.py and djangomanage.py live inside pyon somewhere?

EDIT: Speaking of which, if we're going to be doing something like pyon-admin startproject, then we're going to need to have some templates somewhere that're dumped into the root of the new project when the users starts it up.

**Comment by ShaneDrury** [comment]
The template for manage.py will eventually live in pyon. But yeah at the minute, it's in pyon-qed for testing. I might use Jinja2 again to produce the script.

**Comment by ShaneDrury** [comment]
The version we based our pyon-admin.py off of was from the dev branch i.e. 1.8 alpha0. The current stable release is Django 1.6.5 which has some differences in `django.core.management`. I suggest we change Pyon to use a stable release of Django i.e. 1.6.5. since that is what is installed by default when using dependencies.

EDIT:
Fixed in 30cf952eb7ea431228dcafb84c4df994c413c30c

**Comment by ShaneDrury** [comment]
Fixed in 7199c7c606bd993a2f5d62601ca15be2444ccd0b
